// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcDNFPc7ePzoqQLo_i2skKTX59hJZVfDw',
    appId: '1:880609682091:web:e0761d6fe5c31e5efe4dee',
    messagingSenderId: '880609682091',
    projectId: 'car-service-app-c312c',
    authDomain: 'car-service-app-c312c.firebaseapp.com',
    storageBucket: 'car-service-app-c312c.firebasestorage.app',
    measurementId: 'G-VY9W2GHKL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1aVO0xkwNddFL79-apklumkmnAPkaS5I',
    appId: '1:880609682091:android:7ce72157ac524647fe4dee',
    messagingSenderId: '880609682091',
    projectId: 'car-service-app-c312c',
    storageBucket: 'car-service-app-c312c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABez8bQs8R_yYC16Ki57yroMYtFPWpg94',
    appId: '1:880609682091:ios:7ea47cc976dd3ccefe4dee',
    messagingSenderId: '880609682091',
    projectId: 'car-service-app-c312c',
    storageBucket: 'car-service-app-c312c.firebasestorage.app',
    iosBundleId: 'com.example.carBookingManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABez8bQs8R_yYC16Ki57yroMYtFPWpg94',
    appId: '1:880609682091:ios:7ea47cc976dd3ccefe4dee',
    messagingSenderId: '880609682091',
    projectId: 'car-service-app-c312c',
    storageBucket: 'car-service-app-c312c.firebasestorage.app',
    iosBundleId: 'com.example.carBookingManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcDNFPc7ePzoqQLo_i2skKTX59hJZVfDw',
    appId: '1:880609682091:web:791f1644e33f4642fe4dee',
    messagingSenderId: '880609682091',
    projectId: 'car-service-app-c312c',
    authDomain: 'car-service-app-c312c.firebaseapp.com',
    storageBucket: 'car-service-app-c312c.firebasestorage.app',
    measurementId: 'G-5LWV46ZF39',
  );
}
